name: Build_and_Push

on:
  workflow_dispatch:

env:
  APP_NAME: 'GameDevsConnect'
  APP_NAME_LOWER: 'gamedevsconnect'
    
jobs:
  build-stage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - path: Backend.API.Azure
            lower: backend_api_azure
        # path:
        #   - Backend.API.Azure
        #   - Backend.API.Comment
        #   - Backend.API.File
        #   - Backend.API.Gateway
        #   - Backend.API.Notification
        #   - Backend.API.Profile
        #   - Backend.API.Project
        #   - Backend.API.Request
        #   - Backend.API.Tag
        #   - Backend.API.User
        #   - Frontend

        # path_lower:
        #   - backend_api_azure
        #   - backend_api_comment
        #   - backend_api_file
        #   - backend_api_gateway
        #   - backend_api_notification
        #   - backend_api_profile
        #   - backend_api_project
        #   - backend_api_request
        #   - backend_api_tag
        #   - backend_api_user
        #   - frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./${{env.APP_NAME}}.${{matrix.service.path}}/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{env.APP_NAME_LOWER}}_${{matrix.service.lower}}:latest